import matplotlib.pyplot as plt
import numpy as np
import variance_calcs as vc
from parser import SIPParser
from portfolio import Portfolio
from sample_portfolios import RandomPortfolios

def plot_rand(random_ports):
   """
   Plots [count] random portfolios generated by RandomPortfolios class, standard deviation vs average return
   :param random_ports: a RandomPortfolios object with n Dirichlet-random weighted portfolios
   """
   
   # Create arrays of points to plot
   xs = []
   ys = []
   count = len(random_ports)

   # Populate arrays with standard deviation and average return values of random ports
   for i in range(count):
      xs.append(np.sqrt(random_ports[i]['metadata']['Variance']))
      ys.append(random_ports[i]['metadata']['AverageReturn'])
   
   plt.scatter(xs, ys, s=15)

def plot_frontier(group_data):
   """
   Plots the 'Markowitz bullet'/efficient frontier
   :param group_data: SIP trial data
   """
   a, b, c, ymax = vc.compute_coeffs(group_data)

   # Markowitz bullet equation
   y = np.arange(b/(2 * a), ymax)
   x = np.sqrt((a * y ** 2) - b * y + c)

   plt.plot(x, y, 'r')

def visualize_portfolios(group_data, count):
   """
   Generates random portfolios and plots them with efficient frontier
   :param group_data: samples to generate with
   :param count: number of random portfolios to generate
   """
   gen = RandomPortfolios()
   sample_ports = gen.generate_sample(group_data, count=count)

   # plot generated portfolios and label graph
   plot_frontier(group_data)
   plot_rand(sample_ports)
   plt.xlabel("Risk (Std Dev)")
   plt.ylabel("Average Return ($)")
   plt.title(f"Random portfolios ({count} samples) & Efficient Frontier")
   plt.grid(ls="--")
   plt.show()

def pareto_plot(group_data, count):
   gen = RandomPortfolios()
   sample_ports = gen.generate_sample(group_data, count=count)

   xs = []
   ys = []
   pfx = []
   pfy = []

   for port in sample_ports:
      if port['metadata']['IsParetoEff'] == True:
         pfx.append(port['metadata']['PercentileOM'])
         pfy.append(port['metadata']['AverageReturn'])
      else:
         xs.append(port['metadata']['PercentileOM'])
         ys.append(port['metadata']['AverageReturn'])
   
   plt.scatter(xs, ys, s=15)
   plt.scatter(pfx, pfy, marker='*')
   plt.show()

if __name__ == "__main__":
   SLURP = SIPParser("data/mock_sipmath_v2.xlsx")
   # SLURP = SIPParser("data/small_SIP.xlsx")
   group_data = SLURP.investments
   count = int(input("How many Dirichlet-random portfolios would you like to generate? "))
   visualize_portfolios(group_data, count=count)
   # pareto_plot(group_data, count=count)
