import matplotlib.pyplot as plt
import numpy as np
from parser import SIPParser
from sample_portfolios import RandomPortfolios

def plot_dirichlet(random_ports):
   """
   Plots [count] random portfolios generated by RandomPortfolios class, standard deviation vs average return
   """
   xs = []
   ys = []
   count = len(random_ports)

   for i in range(count):
      xs.append(np.sqrt(random_ports[i]['metadata']['Variance']))
      ys.append(random_ports[i]['metadata']['AverageReturn'])
   
   plt.scatter(xs, ys)


# TODO: move these calcs BACK over to eff_frontier.py so this module isn't too bogged down with math and can add more graphing functionalities (binary toggle, efficient portfolios, etc.)
def create_matrices(group_data):
   """
   Compiles individual asset mean & variance data into matrices for efficient-frontier calculations
   """
   # Step 1: Create empty ndarray to store mean values, NxN matrix for variances
   mu_hat = np.empty(len(group_data))
   sig_matrix = np.empty((len(group_data), len(group_data)))

   # Step 2: Initialize mu_hat, sig_matrix with avg return & variance for each SIP
   for sip in group_data:
      nptrials = np.array(sip['trials'], dtype='f')

      mu_hat[sip['group_index']] = np.average(nptrials) * sip['metadata']['ExpectedRevenue']
      sig_matrix[sip['group_index']][sip['group_index']] = np.var(nptrials) * sip['metadata']['ExpectedRevenue']

   # Step 3: Populate covariance values with 0
   # TODO: Implement covariance calcs for investment tethering functionality
   for i in range(len(group_data)):
      for j in range(len(group_data)):
         if sig_matrix[i][j] == None:
            sig_matrix[i][j] = 0
   
   unit_vector = np.empty(len(group_data))
   unit_vector.fill(1)

   # Turns mu_hat, unit_vector into vectors (1 row, n columns) for matrix operations
   mu_hat = mu_hat.transpose()
   unit_vector = unit_vector.transpose()

   sig_inverse = np.linalg.inv(sig_matrix)

   return mu_hat, sig_inverse, unit_vector

def compute_coeffs(group_data):
   """
   Computes numerical coefficients for efficient-frontier equation, given SIP data on mean & variance
   """
   mu_hat, sig_inverse, unit_vector = create_matrices(group_data)

   # Finds maximum avg return value (for graphing purposes)(this should prob go somewhere else)
   ymax = np.max(mu_hat.transpose())

   # Computes individual terms in denominator expression
   x = np.matmul(np.matmul(mu_hat.transpose(), sig_inverse), mu_hat)
   y = np.matmul(np.matmul(unit_vector.transpose(), sig_inverse), unit_vector)
   z = np.matmul(np.matmul(unit_vector.transpose(), sig_inverse), mu_hat)

   denom = x * y - (z ** 2)

   # Computes numerical coefficients in efficient-frontier equation
   a = (np.matmul(np.matmul(unit_vector.transpose(), sig_inverse), unit_vector)) / denom
   b = 2 * (np.matmul(np.matmul(unit_vector.transpose(), sig_inverse), mu_hat)) / denom
   c = (np.matmul(np.matmul(mu_hat.transpose(), sig_inverse), mu_hat)) / denom

   return a, b, c, ymax

def plot_frontier(group_data):
   """
   Plots the 'Markowitz bullet'/efficient frontier
   """
   a, b, c, ymax = compute_coeffs(group_data)

   y = np.arange(b/(2 * a), ymax)
   x = np.sqrt((a * y ** 2) - b * y + c)

   plt.plot(x, y, 'r')

def visualize_portfolios(group_data, count):
   """
   Generates random portfolios and plots them with efficient frontier
   :param group_data: samples to generate with
   :param count: number of random portfolios to generate
   """
   gen = RandomPortfolios()
   sample_ports = gen.generate_sample(group_data, count=count)

   # plot generated portfolios and label graph
   plot_frontier(group_data)
   plot_dirichlet(sample_ports)
   plt.xlabel("Risk (Std Dev)")
   plt.ylabel("Average Return ($)")
   plt.title(f"Random portfolios ({count} samples) & Efficient Frontier")
   plt.show()

if __name__ == "__main__":
   SLURP = SIPParser("data/mock_sipmath_v2.xlsx")
   # SLURP = SIPParser("data/small_SIP.xlsx")
   group_data = SLURP.investments
   count = int(input("How many Dirichlet-random portfolios would you like to generate?\n"))
   visualize_portfolios(group_data, count=count)
