import matplotlib.pyplot as plt
import numpy as np
import variance_calcs as vc
from parser import SIPParser
from portfolio import Portfolio
from sample_portfolios import RandomPortfolios

class TooltipManager:
   def __init__(self, ax, canvas=None):
      self.ax = ax
      self.fig = ax.figure
      self.scatters = []
      self.randpts = []
      self.effpts = []
      self.annot = ax.annotate("", xy=(0,0), xytext=(20,20), textcoords="offset points", bbox=dict(boxstyle="round", fc="w"), arrowprops=dict(arrowstyle="->"))
      self.annot.set_visible(False)
      if canvas is None:
         self.canvas = self.fig.canvas
      else:
         self.canvas = canvas

      self.fig.canvas.mpl_connect("motion_notify_event", self.hover)
      self.fig.canvas.mpl_connect("pick_event", self.on_pick)
   
   def add_scatter(self, *args, **kwargs):
      if "picker" not in kwargs:
         kwargs["picker"] = True
      sc = self.ax.scatter(*args, **kwargs)
      self.scatters.append(sc)
      return sc

   def update_annot(self, sc, ind):
      pos = sc.get_offsets()[ind["ind"][0]]
      self.annot.xy = pos
      xval = np.around(pos[0], 2)
      yval = np.around(pos[1], 2)
      index = sc.format_cursor_data(ind["ind"] + 1)
      text = f"{index}\n({xval}, {yval})"
      self.annot.set_text(text)
      self.annot.get_bbox_patch().set_alpha(0.4)
   
   def hover(self, event):
      vis = self.annot.get_visible()
      if event.inaxes == self.ax:
         for sc in self.scatters:
            cont, ind = sc.contains(event)
            if cont:
               self.update_annot(sc, ind)
               self.annot.set_visible(True)
               self.fig.canvas.draw_idle()
               return
         if vis:
            self.annot.set_visible(False)
            self.fig.canvas.draw_idle()

   def on_pick(self, event):
      random = self.scatters[0]
      efficient = self.scatters[1]

      if event.artist == random:
         ind = int(event.ind)
         risk = np.around(np.sqrt(self.randpts[ind]['metadata']['Variance']), 2)
         avreturn = np.around(self.randpts[ind]['metadata']['AverageReturn'], 2)
         weights = self.randpts[ind]['weights']
         print(f"Random Portfolio #{ind + 1}:\nAverage Return: ${avreturn} | Risk (std dev): ${risk}\nAsset Weights: {weights}")
      elif event.artist == efficient:
         ind = int(event.ind)
         avreturn = np.around(self.effpts[ind]['metadata']['AverageReturn'], 2)
         risk = np.around(np.sqrt(self.effpts[ind]['metadata']['Variance']), 2)
         weights = self.effpts[ind]['weights']
         print(f"Efficient Portfolio #{ind + 1}:\nAverage Return: ${avreturn} | Risk (std dev): ${risk}\nAsset Weights: {weights}")

   

def plot_rand(random_ports):
   """
   Plots [count] random portfolios generated by RandomPortfolios class, standard deviation vs average return
   :param random_ports: a RandomPortfolios object with n Dirichlet-random weighted portfolios
   """
   
   # Create arrays of points to plot
   xs = []
   ys = []
   count = len(random_ports)

   # Populate arrays with standard deviation and average return values of random ports
   for i in range(count):
      xs.append(np.sqrt(random_ports[i]['metadata']['Variance']))
      ys.append(random_ports[i]['metadata']['AverageReturn'])
 
   return xs, ys

def plot_frontier(group_data):
   """
   Plots the 'Markowitz bullet'/efficient frontier
   :param group_data: SIP trial data
   """
   a, b, c, ymax = vc.compute_coeffs(group_data)

   # Markowitz bullet equation
   y = np.arange(b/(2 * a), ymax)
   x = np.sqrt(a * (y ** 2) - b * y + c)

   eff_points = []
   mu_p = b/(2 * a)
   while mu_p <= ymax:
      port = Portfolio()
      eff_points.append(port.construct_port(group_data, 'e', mu_p))
      mu_p += 10000
   
   xs = []
   ys = []
   for i in range(len(eff_points)):
      xs.append(np.sqrt(eff_points[i]['metadata']['Variance']))
      ys.append(eff_points[i]['metadata']['AverageReturn'])

   # plt.plot(x, y, 'r', ls='--')
   return xs, ys, eff_points

def visualize_portfolios(group_data, count):
   """
   Generates random portfolios and plots them with efficient frontier
   :param group_data: samples to generate with
   :param count: number of random portfolios to generate
   """
   gen = RandomPortfolios()
   sample_ports = gen.generate_sample(group_data, count=count)

   rx, ry = plot_rand(sample_ports)
   ex, ey, effpts = plot_frontier(group_data)
   
   fig, ax = plt.subplots()
   tm = TooltipManager(ax)
   tm.add_scatter(rx, ry, c='b', s=15, picker=True, pickradius=5)
   tm.add_scatter(ex, ey, c='r', marker='*', picker=True, pickradius=5)
   tm.randpts = sample_ports
   tm.effpts = effpts

   ax.plot(ex, ey, c='r', ls='--')
   ax.set_xlabel("Risk (Std Dev)")
   ax.set_ylabel("Average Return ($)")
   ax.set_title(f"Random portfolios ({count} samples) & Efficient Frontier")
   ax.grid(ls="--")

   # plt.xlabel("Risk (Std Dev)")
   # plt.ylabel("Average Return ($)")
   # plt.title(f"Random portfolios ({count} samples) & Efficient Frontier")
   # plt.grid(ls="--")
   # plt.show()   # swap to returning the figure for integration with UI
   return fig, tm, sample_ports, effpts

""" def pareto_plot(group_data, count):
   gen = RandomPortfolios()
   sample_ports = gen.generate_sample(group_data, count=count)

   xs = []
   ys = []
   pfx = []
   pfy = []

   for port in sample_ports:
      if port['metadata']['IsParetoEff'] == True:
         pfx.append(port['metadata']['PercentileOM'])
         pfy.append(port['metadata']['AverageReturn'])
      else:
         xs.append(port['metadata']['PercentileOM'])
         ys.append(port['metadata']['AverageReturn'])
   
   plt.scatter(xs, ys, s=15)
   plt.scatter(pfx, pfy, marker='*')
   plt.show() """

if __name__ == "__main__":
   SLURP = SIPParser("data/mock_sipmath_v2.xlsx")
   # SLURP = SIPParser("data/small_SIP.xlsx")
   group_data = SLURP.investments
   count = int(input("How many Dirichlet-random portfolios would you like to generate? "))
   visualize_portfolios(group_data, count=count)
   # pareto_plot(group_data, count=count)
